worker_processes auto;
events { worker_connections 1024; }

http {
  upstream backend1 {
    least_conn;
    server 127.0.0.1:8000;
  }

  upstream backend2 {
    least_conn;
    server 127.0.0.1:8001;
  }

  server {
    listen 60080;
    location / {
      proxy_pass http://backend1;
      auth_basic "Restricted";
      auth_basic_user_file /etc/nginx/conf.d/.htpasswd;
    }
  }

  server {
    listen 60081;
    location / {
      proxy_pass http://backend2;
      auth_basic "Restricted";
      auth_basic_user_file /etc/nginx/conf.d/.htpasswd;
    }
  }
}

